Repository US-EPA-CAMD/easey-mdm-api, pull requests merged in 2021-07, with the labels that each got.

#27 Unit tests
  src/bypass-approach-code/bypass-approach-code.controller.spec.ts
  src/bypass-approach-code/bypass-approach-code.controller.ts
  src/bypass-approach-code/bypass-approach-code.repository.ts
  src/bypass-approach-code/bypass-approach-code.service.spec.ts
  src/bypass-approach-code/bypass-approach-code.service.ts
  src/parameter-code/parameter-code.controller.spec.ts
  src/parameter-code/parameter-code.controller.ts
  src/parameter-code/parameter-code.module.ts
  src/parameter-code/parameter-code.repository.ts
  src/parameter-code/parameter-code.service.spec.ts
  src/parameter-code/parameter-code.service.ts
  src/sub-data-code/sub-data-code.controller.spec.ts
  src/sub-data-code/sub-data-code.controller.ts
  src/sub-data-code/sub-data-code.repository.ts
  src/sub-data-code/sub-data-code.service.spec.ts
  src/sub-data-code/sub-data-code.service.ts
Labels: Emissioners

#28 Release pipeline
  .github/workflows/develop-branch.yml
  .github/workflows/feature-branch.yml
  .github/workflows/release-branch.yml
  .github/workflows/staging-deployment.yml.disable
  .github/workflows/test-deployment.yml.disable
Labels: DevOps, Tech Team

#30 feature/29-Update-README-files-in-repos-with-disclaimer
  README.md
Labels: Tech Team

#31 add mats method codes mats method param codes
  src/app.module.ts
  src/dto/mats-method-code.dto.ts
  src/dto/mats-method-param-code.dto.ts
  src/entities/mats-method-code.entity.ts
  src/entities/mats-method-parameter-code.entity.ts
  src/mats-method-code/mats-method-code.controller.spec.ts
  src/mats-method-code/mats-method-code.controller.ts
  src/mats-method-code/mats-method-code.module.ts
  src/mats-method-code/mats-method-code.repository.ts
  src/mats-method-code/mats-method-code.service.spec.ts
  src/mats-method-code/mats-method-code.service.ts
  src/mats-method-param-code/mats-method-param-code.controller.spec.ts
  src/mats-method-param-code/mats-method-param-code.controller.ts
  src/mats-method-param-code/mats-method-param-code.module.ts
  src/mats-method-param-code/mats-method-param-code.repository.ts
  src/mats-method-param-code/mats-method-param-code.service.spec.ts
  src/mats-method-param-code/mats-method-param-code.service.ts
  src/routes.ts
Labels: Emissioners

#32 Bug/1482 Update Allowance Program filter to include OTC and NBP
  src/dto/program.dto.ts
  src/dto/program.params.dto.ts
  src/entities/program-code.entity.ts
  src/maps/program.map.ts
  src/mats-method-code/mats-method-code.controller.spec.ts
  src/mats-method-code/mats-method-code.repository.spec.ts
  src/mats-method-code/mats-method-code.service.spec.ts
  src/mats-method-param-code/mats-method-param-code.controller.spec.ts
  src/mats-method-param-code/mats-method-param-code.controller.ts
  src/mats-method-param-code/mats-method-param-code.repository.spec.ts
  src/mats-method-param-code/mats-method-param-code.service.spec.ts
  src/method-code/method-code.controller.spec.ts
  src/method-code/method-code.controller.ts
  src/method-code/method-code.repository.spec.ts
  src/method-code/method-code.repository.ts
  src/method-code/method-code.service.spec.ts
  src/method-code/method-code.service.ts
  src/parameter-code/parameter-code.repository.spec.ts
  src/programs/program-code.repository.spec.ts
  src/programs/program-code.repository.ts
  src/programs/programs.service.spec.ts
Labels: Datateers
